# Generated by Django 4.1.3 on 2022-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersmodel",
            name="customaddress",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
