"""
Django settings for mydjango project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sm%*kzf!-32qo@gt2yl_)$tbt1=sycj8u5iyfdr+c0adzdnqe*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 若正式上線時，請改為 Flase

ALLOWED_HOSTS = ['*'] # 允許所有主機都可以連入
# ['192.168.10.1','203.110.123.10'] 允許這兩個IP連入

# Application definition

# 新增的 app 要新增進去

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'news',
    'product', 
    'abouts', # 111-11-15
    'message', # 111-11-15
    'performance', # 111-11-15
    'cart', # 111-11-17
    'member', # 111-11-24
    
    'photos', # 111-12-06 圖片上傳 
    # 要在 169 行 新增照片上傳存放的地方
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mydjango.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,"templates").replace('\\','/')],  # 在 根目錄建立 templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mydjango.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# 在資料庫建立完資料後，才來這 底下的路徑有介紹
# C:\meetjob\mydjango\mydjango 

import pymysql

pymysql.install_as_MySQLdb()

# 串接的資料庫  
DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydjango',
        'USER': 'myuser',
        'PASSWORD': 'lcclcc',
        'HOST': 'localhost',
        'PORT':'3306',
        'init_command':'SETsql_mode="STRICT_TRANS_TABLES"', 
        # 把 .models 的功能 正常啟動起來 ，如果一般方式不能
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/


# 設定後台

LANGUAGE_CODE = "zh-Hant" # 設定後台界面為繁體中文

TIME_ZONE = "Asia/Taipei" # 亞洲/台北

USE_I18N = True

USE_TZ = False # 不使用當地時間，使用 TIME_ZONE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 在根目錄新增 static 裡面放 css, js, img
STATIC_URL = "static/"

# static_根目錄 
STATIC_ROOT = os.path.join(BASE_DIR,'static')

# staticfiles_目錄
STATICFILES_DIRS = (
    ('images',os.path.join(STATIC_ROOT,'images').replace('\\','/')),
    
    ('css',os.path.join(STATIC_ROOT,'css').replace('\\','/')),
    
    ('js',os.path.join(STATIC_ROOT,'js').replace('\\','/')),
    
    )

# 111-12-01  設定瀏覽器關閉時， session 就關掉 True 是關掉 ， 預設是 Flase => 不關
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# 111-12-06 設定多媒體的資料夾位置

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
